index.d.ts

Looks like this was missed in the previous MR addressing variants (https://github.com/figma/plugin-typings/pull/10)
I ran into this while writing some code that acts on nodes based on their types. The type string for `ComponentSet`s is not available.
This PR is based on a very shallow understanding of the typings file and the changes made by the previous PR, as such I might've missed something important. Feel free to point out any improvements I should make and I'll try to get those in!

Add ComponentSets to SceneNode and NodeType

---

index.d.ts

Adds the CHANGE_TO navigation type, new for interactive components. Reactions are still read-only

Update typings for interactive component navigation type

---

index.d.ts

Callign notify with `{error:true}` makes the notification show up with
a red error background.

add 'error' field to NotificationOptions

---

index.d.ts

This PR adds additional typings for the new stamp node type for FigJam plugins. Stamps, for now, are only readable so this just creates appropriate types for them.
While `name` should be one of `Thumbs up`, `Star`, etc we leave it as a `string` since users can rename them when pasted into Design Figma.

add stamp typings for FigJam plugins launch

---

index.d.ts
package.json

Adds types for plugin parameter APIs:
- `figma.on('run')`
- `figma.parameters.on('input')`
- `setSuggestions`

Add types for plugin parameters

---

index.d.ts
package.json

This is more generic and allows us to modify `ParameterValues` in the future without breaking the API.

Change type for `ParameterValues` to `any`

---

index.d.ts
tsconfig.json

Figma plugins run in a restricted environment where the browser APIs
aren't available by default, including 'console'.  This means the plugin
typings should declare exactly what console API is available.  (Note that
the functions listed here are a subset of the full browser console API;
these are the subset that plugins actually have access to.)
This change also adds a tsconfig.json to this repo, because otherwise
TypeScript thinks this definition of console conflicts with the ambient
browser one.

console API types and tsconfig.json

---

index.d.ts
package.json

Fix bad merge conflict caused by [this](https://github.com/figma/plugin-typings/commit/5604eefdbdf6671937bf65e496251644c168893f) clobbering [this](https://github.com/figma/plugin-typings/commit/0d32751)
I checked the rest of the big diff earlier and this is the last change that was affected

add text range functions again

---

package.json

Change `npm test` to run tsc with no arguments, so it picks up the local
tsconfig.json.  In particular this makes it obey the 'lib' setting found
there.  (Currently `npm test` fails due to this.)

use tsconfig for npm test configuration

---

index.d.ts

Much like the console API, we support a subset of the functionality that a browser
exposes.

add timeout-related API

---

index.d.ts

Add missing `EASE_IN_BACK`, `EASE_OUT_BACK`, `EASE_IN_AND_OUT_BACK`, `CUSTOM_CUBIC_BEZIER` easing types as documented here: https://www.figma.com/plugin-docs/api/Transition/#docsNav
Addresses: https://github.com/figma/plugin-typings/issues/20

Add full set of Easing types

---

index.d.ts

Adds `CodeBlockNode` and `figma.createCodeBlock` types.

Add CodeBlockNode and createCodeBlock typings

---

plugin-api.d.ts

Adds typings for the new storage APIs.
I wasn't sure if making BaseNodeMixin inherit PluginDataMixin would trip up the documentation checking code, since I didn't want to use inheritance there, so went for a simpler solution

New storage APIs

---

plugin-api.d.ts

Add typings for `figma.skipInvisibleInstanceChildren`, `node.findAllWithCriteria`, and `node.findAllByType`

Add typings for faster findAll functions

---

plugin-api.d.ts

Add stricter typings for `node.findAllWithCriteria` in the plugin API, which removes the need for `node.findAllByType`.

Stricter typings for findAllWithCriteria; remove findAllByType

---

package.json
plugin-api.d.ts

The `getBytesAsync` and `getTextAsync` functions in the `DropFile` interface in the plugin API were incorrectly declared as properties when they are actually supposed to be functions. This PR fixes the typings.

Fix typing bug where we declared DropFile functions as properties

---

plugin-api.d.ts

This adds types for both the washi tape(added to FigJam this week) and highlight nodes (added to FigJam 4 or 5 months ago). 
Test Plan:
- I wrote a little plugin that logs the nodes if they are the new type to make sure typescript is happy:
```
const selection = figma.currentPage.selection;
for (const node of selection) {
if (node.type === "WASHI_TAPE") {
console.log(node);
} else if (node.type === "HIGHLIGHT") {
console.log(node);
}
}
figma.closePlugin();
```

plugin-typings: Add washi tape and highlight node types

---

plugin-api.d.ts

Sibling PR of https://github.com/figma/figma/pull/63122.
This PR adds the `CIRCLE_FILLED` option to the `ConnectorStrokeCap` type, to support the new circle end cap added in https://github.com/figma/figma/pull/63058.
I don't plan on merging this PR until close to when we flip the circle endcap feature flag on for everyone, which shouldn't be until at least 4/13/22

Add CIRCLE_FILLED connector stroke cap type

---

plugin-api.d.ts

Based on internal types, I don't see why opacity or blend mode should be optional. I also updated BlendMode to include `PASS_THROUGH`, which is consistent with our implementation.

Dedupe blend and minimal blend

---

plugin-api.d.ts

Types have been updated to match changes to the plugin API documentation for component properties [here](https://github.com/figma/figma/pull/71474). Here is the [paper doc](https://paper.dropbox.com/doc/Component-Props-Finalize-API-Documentation--Bj61Yhzh26znUSCZUYys8~UmAg-X5fZlCf7ZzFykLr6JJ1oW) for changes being made to the documentation. 
Confirmed that running the tests in `/plugin-docs/tests` passes with these new types but will hold on merging this PR until the PR linked above is finalized and approved (but not merged).

Update types for Component Properties support

---

plugin-api.d.ts

Fix typo in LayerSublayerNode interface name

Rename LayerSublayerNode (with typo) to LabelSublayerNode

---

plugin-api.d.ts

This adds the type for getAuthorAsync.
Ideally I would name the existing `User` to `MultiplayerUser` and make what is now `BaseUser` -> `User`, but I don't want to break anyone who depends on these typings.

Add getAuthorAsync to stamps

---

plugin-api.d.ts

This adds attachedConnectors for SceneNode which returns an array of connectors that are attached to a node.
Note that while doing this I also realized that stuckNodes should be `readonly`, so I updated that as well.

Add attachedConnectors field for SceneNode

---

plugin-api.d.ts

Bash is now supported as a code block language.

Add Bash language to code block enum

---

plugin-api.d.ts
test-usage.sh

This PR adds new parameters to the `notify` API. It adds `button`, `onDequeue`, and `NotifyDequeueReason`. The documentation changes are at: https://github.com/figma/figma/pull/73090

Added button and onDequeue typings for notify

---

test-usage.sh

This makes sure that we test the same as our default plugin typings.

Add strict: true to tsconfig.json in our tests

---

plugin-api.d.ts

Forgot to update `ComponentProperties` type with `preferredValues`. Main PR here: https://github.com/figma/figma/pull/82156

plugins: update props typings

---

plugin-api.d.ts

I can't find this in the Figma documentation page, but according to the implementation `fontWeight` is a supported property of `getStyledTextSegments`
eg.

Add fontWeight to StyledTextSegment

---

plugin-api.d.ts

https://github.com/figma/plugin-typings/pull/148 added types for `fontWeight` to `StyledTextSegment` but we also added `getRangeFontWeight` so adding types for this as well - implementation here: https://github.com/figma/figma/pull/74934
Test Plan
- assert that the types match those for the implementation

plugins: add plugin typings for getRangeFontWeight

---

plugin-api.d.ts

Update the typings in `InstanceNode` to expect `exposedInstances` and `isExposedInstance` properties. Changes added here: https://github.com/figma/figma/pull/82869 and https://github.com/figma/figma/pull/82049

plugins: add exposed instance properties to API typings

---

index.d.ts
plugin-api.d.ts

This adds typings for `createNodeFromJSXAsync`
I ended up porting the types for `FigmaDeclarativeNode` into plugin-typings since they are very small and haven't really changed since we have released widgets, so it should be easy to just ask people to install the widget typings if they want to use the components from the JSX api

Add createNodeFromJSXAsync

---

plugin-api.d.ts

`AddComponentProperty` does not support type: 'VARIANT' so lets update the type to reflect that:
See: https://www.figma.com/plugin-docs/api/node-properties#addcomponentproperty

Update typings for addComponentProperty

---

plugin-api.d.ts

This change renames `createVideo(...): Video` to `createVideoAsync(...): Promise<Video>`.

Renamed createVideo to createVideoAsync

---

plugin-api.d.ts

I'll be enabling `ee_ind_borders_plugin_api` soon which makes `strokeWeight` return mixed if individual stroke weight values are used per side. This updates the plugin typings to reflect this.
Related docs change: https://github.com/figma/figma/pull/77996

Update strokeWeight return to include mixed

---

index.d.ts

This adds the `headers` property to fetch requests, a `json` method to the response, and `body` can take a string.

Make fetch more in line with the standard

---

plugin-api.d.ts

We want to make the plugin docs the source of truth. This PR removes redundant comments from the plugin-typings repo. All of the commented information is available in the plugin docs at https://www.figma.com/plugin-docs. This way, it'll be easier for us to automatically generate the plugin-typings file.

Remove comments from plugin-typings repo

---

plugin-api.d.ts

Instead of re-defining expanded on BooleanOperationNodes, use the ContainerMixin so that the properties get coalesced properly in our docs eg. https://www.figma.com/plugin-docs/api/node-properties/#expanded

typings: Make BooleanOperationNode extend ContainerMixin

---

plugin-api.d.ts

`TextCase` now supports `"SMALL_CAPS"` and `"SMALL_CAPS_FORCED"` too.

Add "SMALL_CAPS" and "SMALL_CAPS_FORCED" to `TextCase`

---

plugin-api.d.ts

The `visible`, `characters`, and `mainComponent` in `componentPropertyReferences` should be optional, not required.

Make properties in componentPropertyReferences optional

---

plugin-api.d.ts

Update plugin typings for spring animations to include spring animation presets and custom function.

Update plugin typings for spring animations

---

plugin-api.d.ts

Can do `node.exportAsync({ format: 'SVG_STRING' })` now.

SVG_STRING format for exportAsync

---

plugin-api.d.ts

We added `PLAINTEXT` as a code block language some time ago, but didn't add it to plugin docs. Now that we're removing the feature flag for it on https://github.com/figma/figma/pull/136343, it's a good time to do it.

adds PLAINTEXT to code block languages

---

plugin-api.d.ts

Add `getPluginPaymentTokenAsync` to `payments` API.
Following `plugin-docs/README.md` and ensured that `npm run test` returned `plugin-docs-api.d.ts matches plugin-typings.d.ts`

Typing for figma.payments REST API helper

---

plugin-api.d.ts

This adds plugin typings for the new alv5 properties.
Related documentation PR: https://github.com/figma/figma/pull/120261

add typings for alv5

---

plugin-api.d.ts

This change adds the `isWideWidth` property to the `StickyNode` type.

StickyNode: add isWideWidth property

---

package.json

This version includes the `StickyNode.isWideWidth` property.

version bump to 1.70.0

---

plugin-api.d.ts

addresses https://github.com/figma/plugin-typings/issues/117

fillGeometry and strokeGeometry are readonly

---

plugin-api.d.ts

1) Add cornerRadius to VariableBindableNodeField. [See Discord.](https://discord.com/channels/675194100147945497/899758994204266548/1252984217449791528)
2) Add missing values to StrokeCap. [See Discord.](https://discord.com/channels/675194100147945497/899758994204266548/1253246408455225405)

[web] Fix missing properties in plugin-typings

---

plugin-api.d.ts

This change undoes the removal of nullable modifiers from `boundVariables`, introduced in #303.
`boundVariables` is indeed non-nullable when _reading_ objects from the Plugin API, but several of the affected types, such as [Paint](/api/Paint/) and [Effect](/api/Effect/), are used for _writing_. In the write path, `boundVariables` is optional. Removing the nullable modifier caused typechecker errors in otherwise valid code. The nullable modifier has been added back in 1.99. Apologies to everyone who encountered difficulties, and apologies to anyone affected by the additional churn from this update!
We intend to release a typings update in the future that makes `boundVariables` non-nullable in specific situations, but the second attempt will more carefully address the write path.

undo boundVariables nullability change

---

plugin-api-standalone.d.ts
plugin-api.d.ts

not sure why `declare type` got transformed into `type`
the actual changes are `descriptionMarkdown: string`, `normalizeMarkdown(markdown: string): string`, and `readonly labelMarkdown?: string`

add updates for v1.103
