figma/plugin-typings

index.d.ts, package.json
Update to reflect changes in the implementation.
Test Plan: ran `npm run test` locally.
=> Update InstanceNode.mainComponent to be nullable.

index.d.ts
Add figma.fileKey to the types
Here: https://www.figma.com/plugin-docs/api/figma/#filekey
=> Add fileKey types to typescript

index.d.ts
Paired w/ https://github.com/figma/figma/pull/25546
=> Add __uiFiles__ type

index.d.ts
This PR adds new typings for variants. 
It involves refactoring the `DefaultFrameMixin` interface, as component sets should have many of the default frame properties, but should **not** have some of the other properties (i.e. prototyping-related properties + reactions).
This PR also adds a `PublishableMixin` to unify the publishing-related properties on components, component sets, and styles.
=> new typings for variants

index.d.ts
Update typings for auto layout v3 changes.
Spec: https://paper.dropbox.com/doc/1012020-ALv3-public-API-plugin-API--A_mVMIkHxjRK0MK3NJxl8FmbAg-5IljwtD1egnjHzgU6aLGt
=> Add typing updates for autolayout v3

index.d.ts
Add typings for prototyping scroll action.
=> Add typings for prototyping scroll action

index.d.ts
=> Add typing for API functions to reorder local styles

index.d.ts
=> Add typing for API functions to reorder folders & styles

index.d.ts
* Add typings for documentation links and detach instance.
=> Add new typings for release 23

index.d.ts
This PR updates Triggers to include `ON_KEY_DOWN` typing info
=> update typings for ON_KEY_DOWN trigger

index.d.ts
Typings update for hyperlink APIs on TextNode
=> Hyperlink APIs on TextNode

index.d.ts
Add typings for title field in showUI
=> add title field to ShowUIOptions

index.d.ts
typings for text list support. This was absent on feature launch
=> typing for text list support

index.d.ts, package.json
Add API types for FigJam plugins.
=> figjam plugins: API typings

index.d.ts
=> Add missing getRangeAllFontNames

index.d.ts, package.json
Update API to have variant-related functions and properties added as part of this update: https://www.figma.com/plugin-docs/blog/2021/09/01/version-1-update-33/
=> Update API with variant-related functions

index.d.ts
Fixes https://github.com/figma/plugin-typings/issues/39
=> add typings for commitUndo and triggerUndo

index.d.ts, package.json
Add `flowStartingPoints` to `PageNode`. See https://www.figma.com/plugin-docs/api/PageNode/#flowstartingpoints
=> add flowStartingPoints to PageNode

index.d.ts
Adds typings for the new timer plugin API.
=> Add timer types

index.d.ts
Reverts figma/plugin-typings#42
=> Revert "Add timer types"

.github/workflows/test.yml
This shells out to `npm test` on every PR.
=> actions test

index.d.ts, package.json
Update to support hidden metadata for parameter suggestions, and also updates the event syntax for the 'input' event
=> Update parameter 'input' event syntax

package.json
For https://github.com/figma/plugin-typings/pull/76
=> Bump up patch version for PR #76 merged earlier

index.d.ts, package.json
Add the `absoluteRenderBounds` property that will come out in Update 38.
=> Add absoluteRenderBounds property

index.d.ts
- (Yet to be deployed) Additions to WidgetNode methods
- Bug fixes: Various FigJam Plugin Nodes
=> typings: fix some node related typing discrepancies

index.d.ts, package.json, plugin-api.d.ts
Add createEmbedAsync to the plugins typings.
=> Add createEmbedAsync to typings

plugin-api.d.ts
Update the type declarations for on, once, and off to support the new drop events proposed API.
=> Add "drop" event type to on, once, and off

package.json, plugin-api.d.ts
Add support for connector start/end stroke cap.
=> typings: connector start/end stroke cap

plugin-api.d.ts
Add `getStyledTextSegments` for text nodes for getting mixed text styles.
=> Add getStyledTextSegments for text nodes

plugin-api.d.ts
Add typings for `createGif()`, `MediaNode`, `MediaData`
=> add typings for media nodes

plugin-api.d.ts
Now we return a `VersionHistoryResult`.
=> Update typings for saveVersionHistoryAsync

plugin-api.d.ts
Update the typings to include the createSection api
=> Add createSection api

.github/workflows/test.yml, .prettierrc, package.json, plugin-api.d.ts
Only formatting changes in the typings file; no API changes.
=> Apply prettier to the typings file

plugin-api.d.ts
=> Add typings for stickables

plugin-api.d.ts
Add typings for sticky resize and rescale.
=> Add typings for sticky resize and rescale

plugin-api.d.ts
Add themeColors to the set of options in figma.showUI
=> Add themeColors option to figma.showUI

plugin-api.d.ts
This adds types for the ungroup method added in https://github.com/figma/figma/pull/56080
=> Add ungroup method

plugin-api.d.ts
* absolute positioning
* baseline alignment
* reverse z index
* strokes included in layout
* text truncation
=> Add autolayout v4 properties

plugin-api.d.ts
This adds the individual stroke weight properties discussed here: https://paper.dropbox.com/doc/Individual-Borders-Plugin-API--BiPf2vPm0X8qONZ2d1MCLENFAg-T9rb3k7GL6OSzdDbGEcmc#:uid=600555594735103115770840&h2=Proposed-Change
https://app.asana.com/0/1202275773110317/1202285354275880
=> Add individual stroke weight properties

plugin-api.d.ts
Updating typings. PR to add logic here: https://github.com/figma/figma/pull/82156
=> plugins: add `preferredValues` to props API typings

plugin-api.d.ts
This adds the typings for the `instances` property on components
=> Add typings for the instances property on components

index.d.ts, plugin-api.d.ts
Getting these types happy with the doc generator has proven to be challenging so just marking as any for now
=> Make the parameter of createNodeFromJSXAsync any for now

plugin-api.d.ts
Adding styles create and delete
=> styles create and delete

plugin-api.d.ts
Typings for overrides and resetOverrides() on instanceNodes
=> Plugin API: overrides typings

plugin-api.d.ts
=> Plugin API: documentChanges style deletes return null

plugin-api.d.ts
This PR adds types defined in this PR for documentation:
https://github.com/figma/figma/pull/90504/files
The changes were also discussed here: https://paper.dropbox.com/doc/Video-Plugin-API-Changes--Bpj~OszO3Yc5phgOAdJ1xeigAQ-N8VYAjZzppKxVHB0l4kBM
=> Adding types for the new Video feature

package.json
Bumping version for release of video APIs
=> Bumping version to 1.55 

package.json
Bumping patch version for release of updated `createVideoAsync` method.
=> Bumping version to 1.55.1

plugin-api.d.ts
This adds all of the typings for textreview! This has been the same set of typings that users have been using for the beta.
=> Typings for textreview api

plugin-api.d.ts
The `ui.reposition()` method is coming soon. This change includes typings for it.
=> Add reposition typings

plugin-api.d.ts
=> Dedupe properties to clean up typings

plugin-api.d.ts
Adds typings for new video actions and video triggers.
=> update plugin typings for videos v2

plugin-api.d.ts
https://app.asana.com/0/1203061614517911/1204148478726846/f
=> update typings for leading trim, hanging punctuation, hanging list

plugin-api.d.ts
Our state management feature released and we [have already updated the actual plugin functionality](https://github.com/figma/figma/pull/148721), but now we have to update the docs and typings. This PR is for the typings update
[Related PR](https://github.com/figma/figma/pull/152109)
=> Typings update for state management release

plugin-api.d.ts
Improves types for
* resolvedVariableModes
* explicitVariableModes
* valuesByMode
=> Improves types for a few variables APIs

plugin-api.d.ts
This also backs out some changes @RobbieZhuang is working on. I checked offline that this is fine.
=> Add table cell node to scene node type

plugin-api.d.ts
=> add hidefrompub again

plugin-api.d.ts
We can merge the plugin + rest API documentation immediately after this to keep them in sync! https://github.com/figma/figma/pull/167852
=> Add new shapes back into the typings

plugin-api.d.ts
adding DetachedInfo for https://github.com/figma/figma/pull/177142 (draft!)
=> Add DetachedInfo

plugin-api.d.ts
Add CENTER to connector endpoint magnet (for STRAIGHT connectors)
=> Add CENTER to connector endpoint magnet

plugin-api.d.ts
=> plugin-typings: version 1.90.0

plugin-api-standalone.d.ts, plugin-api.d.ts
Fix to `getRangeBoundVariable`
=> March 17 updates
